[supabase]
url = "https://ghhxvadnzdgdllqghlzr.supabase.co"
key = "sb_publishable_RJzInAz3TN4bEBqVqyDE5A_4TGmIyPF"

[openrouter]
api_key = "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"